version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db-messenger
    environment: 
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: Messenger123
        POSTGRES_DB: MessengerApp
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - backend
volumes:
    postgres_data:
networks:
    backend:
        driver: bridge    
    